### ISSUE TITLE
Security and stricting token

### ISSUE THREAD

**Issue by oshliaer** [tanaikech/ResumableUploadForGoogleDrive_js#2]
Thanks for the great tool!

It works PERFECTLY from the box!

But I host the html page on an external web-server. So I need to know did you think about security and stricting a token at this perspective?

I'm planing try restrict project auth but I think it's not possible for a gas project key.

**Comment by tanaikech** [comment]
Thank you for your comment, and I'm sorry my late replying. I noticed your comment just now. Sorry.

About the security, for example, in that case, how about using the specific folder with the service account and the scope of `https://www.googleapis.com/auth/drive.file`? By this, the files except for the uploaded files cannot be accessed. But, the uploaded files can be accessed. So, for example, after the file was uploaded, how about moving it to other folder?

I'm not sure whether this is the correct direction you expect. I apologize for this.

**Comment by oshliaer** [comment]
You're right. It's that what I think too.

I'll try to hack my app to compromise the token key. Let's see what happens.

Don't close for a week, pls.

**Comment by tanaikech** [comment]
Thank you for replying. Yes. Also, I would like to consider whether other direction can be considered.

**Comment by tanaikech** [comment]
I published a report of [Safe-Uploading for Google Drive by HTML in External Server using Google Apps Script](https://github.com/tanaikech/Safe-Uploading-for-Google-Drive-by-HTML-in-External-Server-using-Google-Apps-Script). Is this useful for your situation?

**Comment by oshliaer** [comment]
Exactly!

We thought about the same things! I'm very glad!

**Comment by tanaikech** [comment]
Thank you for replying!
